#!/bin/sh

export LANG=en_GB.UTF-8
export LOCALE=en_GB.UTF-8
xmodmap $HOME/.config/Xmodmap/Xmodmap
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom/picom.conf --backend xrender &
$HOME/.config/scripts/batterynotification.sh &
nm-applet &
blueberry-tray &
wmname LG3D
killall polybar
killall fusuma
fusuma -c $HOME/.config/fusuma/config.yml &

# start gnome keyring
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# Change System bell sound
pactl upload-sample /usr/share/sounds/freedesktop/stereo/dialog-error.oga bell-window-system
pactl load-module module-x11-bell display=$DISPLAY

### MONITORS

bspc monitor eDP      -d 1 2 3 4 5 6 7 8 9 10
xrandr --output eDP --mode 1920x1080 --set TearFree on
nitrogen --set-zoom-fill ~/Pictures/Wallpaper/Jyv.png

# If external is not empty, set 2 monitors up
#for EXTERNAL in $(xrandr --query | grep " connected" | cut -d" " -f1); do
 
#xrandr --output DisplayPort-0 --mode 1920x1080 --set TearFree on --above eDP
#bspc monitor DisplayPort-0 -d 21 22 23 24 25 26 27 28 29 30
#xrandr --output HDMI-A-0 --mode 1920x1200 --set TearFree on --left-of DisplayPort-0
#bspc monitor HDMI-A-0 -d 11 12 13 14 15 16 17 18 19 20
#
#nitrogen --set-zoom-fill ~/Pictures/Wallpaper/Jyv2.png
#bspc wm --reorder-monitors eDP HDMI-A-0 DisplayPort-0

#3 monitor setup

xrandr --newmode "1920x1200"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
xrandr --addmode DisplayPort-2 1920x1200                                                    
xrandr --output DisplayPort-2 --mode 1920x1200 --set TearFree on --left-of eDP          
xrandr --output DisplayPort-1 --mode 1920x1080 --set TearFree on --left-of DisplayPort-2
bspc monitor eDP -d 21 22 23 24 25 26 27 28 29 30         
bspc monitor DisplayPort-2 -d 11 12 13 14 15 16 17 18 19 20
bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9 10         
bspc wm --reorder-monitors DisplayPort-1 DisplayPort-2 eDP

$HOME/.config/polybar/launch.sh

### CONFIG
bspc config border_width            	2
bspc config window_gap              	5
bspc config split_ratio             	0.52
bspc config borderless_monocle      	true
bspc config gapless_monocle         	true
bspc config focus_follows_pointer       true
bspc config pointer_modifier	        super
bspc config pointer_action1		        move
bspc config pointer_action2		        resize_side
bspc config pointer_action3		        resize_corner
bspc config pointer_motion_interval     40
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

### COLOURS
bspc config active_border_color		"#808080"
bspc config focused_border_color    "#808080"

### RULES
bspc rule -a Gscreenshot		                    state=floating
bspc rule -a Nm-connection-editor 	                state=floating
bspc rule -a Qalculate-gtk		                    state=floating
bspc rule -a Blueberry.py                           state=floating
bspc rule -a Bluetooth                              state=floating
bspc rule -a Pavucontrol                            state=floating
bspc rule -a Zathura                                state=tiled
bspc rule -a Msgcompose                             state=floating
bspc rule -a Tk                                     state=floating
bspc rule -a brave-browser:Picture-in-picture       state=floating
