-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Environment Variables

-- see https://wiki.hyprland.org/Configuring/Environment-variables/ 

-- Theming Related Variables

-- Set cursor size. See FAQ below for why you might want this variable set.

-- https://wiki.hyprland.org/FAQ/

--env = XCURSOR_SIZE,80

-- Set a GTK theme manually, for those who want to avoid appearance tools such as lxappearance or nwg-look

--env = GTK_THEME,Adwaita

-- Set your cursor theme. The theme needs to be installed and readable by your user.
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")


-- XDG Specifications
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("SDL_VIDEODRIVER", "wayland")

-- Steam runtime variable
hl.env("STEAM_RUNTIME", 1)

