-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local SCRIPT = "~/.config/HyprV/waybar/scripts"

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/volume --inc"))
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/volume --dec"))
hl.bind("xf86AudioMicMute", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/volume --toggle-mic"))
hl.bind("xf86audioMute", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/volume --toggle"))
hl.bind("xf86KbdBrightnessDown", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/kb-brightness --dec"))
hl.bind("xf86KbdBrightnessUp", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/kb-brightness --inc"))
hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/brightness --dec"))
hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd("~/.config/HyprV/waybar/scripts/brightness --inc"))
