-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
local smw = require("plugins.split-monitor-workspaces")
smw.setup({
	workspace_count = 10, -- This will create n persistent workspaces on each monitor at startup
	monitor_priority = { "eDP-1", "DP-1", "DP-2", "DP-3" },
})

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@144",
	position = "1540x1100",
	scale = 1,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@144",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "DP-1",
	mode = "1680x1050@144",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "DP-2",
	mode = "1920x1080@60",
	position = "3460x0",
	scale = 1,
})

hl.monitor({
	output = "DP-3",
	mode = "1920x1080@60",
	position = "5380x0",
	scale = 1,
})
